=head1 NAME

CWMP - CPE WAN Management Protocol

=head1 DESCRIPTION

This is free, open source implementation of

DSL Forum: TR-069 - CPE WAN Management Protocol, May 2004

In essence, it's relaxed SOAP server which eats garbage and tries to produce
standard compliant results.

Standard defines following methods:

  CPE methods             Responding  Calling
 
  GetRPCMethods           Required    Optional
  SetParameterValues      Required    Required
  GetParameterValues      Required    Required
  GetParameterNames       Required    Required
  SetParameterAttributes  Required    Optional
  GetParameterAttributes  Required    Optional
  AddObject               Required    Optional
  DeleteObject            Required    Optional
  Reboot                  Required    Optional
  Download                Required    Required
  Upload                  Optional    Optional
  FactoryReset            Optional    Optional
  GetQueuedTransfers      Optional    Optional
  ScheduleInform          Optional    Optional
  SetVouchers             Optional    Optional
  GetOptions              Optional    Optional

  Server methods   Calling    Responding
 
  GetRPCMethods    Optional   Required
  Inform           Required   Required
  TransferComplete Required   Required
  RequestDownload  Optional   Optional
  Kicked           Optional   Optional


To see implemented methods take a look in L<CWMP::Methods>

=head1 AUTHOR

Dobrica Pavlinusic, C<< dpavlin@rot13.org >>
