{
  CurrentTime => "1970-01-01T00:01:31Z",
  DeviceId => {
        Manufacturer => "THOMSON",
        OUI => "00147F",
        ProductClass => "SpeedTouch 780",
        SerialNumber => "CP0644JTHJ4",
      },
  Event => [
        { CommandKey => undef, EventCode => "1 BOOT" },
        { CommandKey => undef, EventCode => "2 PERIODIC" },
        { CommandKey => undef, EventCode => "4 VALUE CHANGE" },
      ],
  ID => "0_THOM_TR69_ID",
  MaxEnvelopes => 2,
  Parameter => {
        ".ExternalIPAddress"                                              => "192.168.1.254",
        "InternetGatewayDevice.DeviceInfo.HardwareVersion"                => "BANT-R",
        "InternetGatewayDevice.DeviceInfo.ProvisioningCode"               => undef,
        "InternetGatewayDevice.DeviceInfo.SoftwareVersion"                => "6.2.15.5",
        "InternetGatewayDevice.DeviceInfo.SpecVersion"                    => "1.1",
        "InternetGatewayDevice.DeviceInfo.VendorConfigFile.1.Date"        => "0000-00-00T00:00:00",
        "InternetGatewayDevice.DeviceInfo.VendorConfigFile.1.Description" => "Factory Defaults",
        "InternetGatewayDevice.DeviceInfo.VendorConfigFile.1.Name"        => "Routed PPPoE on 0/35 and 8/35",
        "InternetGatewayDevice.DeviceInfo.VendorConfigFile.1.Version"     => undef,
        "InternetGatewayDevice.DeviceSummary"                             => "InternetGatewayDevice:1.1[] (Baseline:1, EthernetLAN:1, ADSLWAN:1, Bridging:1, Time:1, WiFiLAN:1)",
        "InternetGatewayDevice.ManagementServer.ConnectionRequestURL"     => "http://192.168.1.254:51005/",
        "InternetGatewayDevice.ManagementServer.ParameterKey"             => undef,
      },
  RetryCount => "05",
  _dispatch => "InformResponse",
}